# Generated by Django 5.2.2 on 2025-06-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shippinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
    ]
