# Generated by Django 5.2.2 on 2025-06-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_contactmessage_newslettersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscription',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
