# Generated by Django 5.2.2 on 2025-06-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_contactmessage_newslettersubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
    ]
