# Generated by Django 5.2.2 on 2025-06-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_newslettersubscription_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscription',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
