# Generated by Django 5.2.2 on 2025-06-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_order_status_remove_order_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
